
# version format
version: 0.6.0 {branch}-{build}

# branches to build
branches:
    # blacklist
    except:
        - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
    - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\trillek-vcomputer-module

# scripts that run after cloning repository
install:
    - cmd: cd c:\projects\trillek-vcomputer-module\
    - ps: c:\projects\trillek-vcomputer-module\prebuild.ps1

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

build_script:
    - cmd: cd c:\projects\trillek-vcomputer-module\
    - ps: c:\projects\trillek-vcomputer-module\build.ps1

test_script:
    - cmd: cd c:\projects\trillek-vcomputer-module\bin\Debug
    - cmd: dir
    - cmd: unit_test.exe

on_success:
    - cmd: cd c:\projects\trillek-vcomputer-module\
    - cmd: msbuild PACKAGE.vcxproj /p:Configuration=Debug /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
